name: firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^0.8.5+3
  lottie: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/63787-secure-login.json
    - assets/71361-sign-in.json
